version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: quay.io/redsift/sandbox-javascript:v16.15.0
    steps:
      - run: ssh -o StrictHostKeyChecking=no git@github.com || true
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm i -g npm@8.18.0

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install && npm test
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - distribution


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
